config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :users, only: [:new, :create]
  resources :items, only: [:index, :show, :create, :update]
  resources :categories, only: [:index, :show]

  namespace :admin do

    get '/dashboard', to: 'dashboard#index'

    resources :orders
    resources :items
    resources :users, only: [:show]
  end

  namespace :patron do
    resources :orders, only: [:new, :create, :index, :show]
    resources :users, only: [:show, :update, :edit]
  end

  get '/dashboard', to: 'dashboard#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/cart', to: 'cart#show'
  post '/cart', to: 'cart#create'
  delete '/cart', to: 'cart#destroy'
  put '/cart', to: 'cart#update'
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user

  has_many :orders_items
  has_many :items, through: :orders_items

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @line_items = OrdersItem.where(order_id: @order.id)
    @purchaser = User.find(@order.user_id)
  end

  def destroy
    @order = Order.find(params[:id])
    delete_order_items(OrdersItem.where(order_id: @order.id))
    @order.destroy

    redirect_to request.referrer
  end

  def update
    @order = Order.find(params[:id])
    @order.update(status: "Completed")
    redirect_to request.referrer
  end

  private

  def order_params
    params.require(:order).permit(:id, :status)
  end

  def delete_order_items(order_items)
    order_items.each do |order_item|
      order_item.destroy
    end
  end
end

app/controllers/patron/orders_controller.rb
class Patron::OrdersController < Patron::BaseController

  def index
    @open_orders = Order.where(user_id: current_user.id, status: "Ordered")
    @closed_orders = Order.where(user_id: current_user.id, status: "Completed")
  end

  def new
    @order = Order.new(user_id: current_user.id)
    if @order.save
      # replicate save method with own method. Possible refactor.
      create_join_table_entries(@order)
      flash[:order_success] = "Order was successfully placed"
      session[:cart] = nil
      redirect_to patron_orders_path
    else
      flash[:cart_error] = "Order could not be placed."
      redirect_to cart_path
    end
  end

  def show
    @order = Order.find(params[:id])
    @line_items = OrdersItem.where(order_id: @order.id)
  end

  private

  def create_join_table_entries(order)
    @cart = session[:cart]
    @cart.each_pair do |item, quantity|
      OrdersItem.create!(order_id: order.id, item_id: item.to_i, quantity: quantity )
    end
  end
end

app/views/admin/orders/index.html.erb
<div class="admin-orders">
  <% @orders.each do |order| %>
  <%= link_to "Order: #{order.id}", admin_order_path(order.id) %>
  Status: <%= order.status %>
  <%= link_to "Complete", admin_order_path(order.id), method: :put, class:"btn btn-success" %>
  <%= link_to "Delete", admin_order_path(order.id), method: :delete, class:"btn btn-danger" %>
  <br>
  <% end %>
</div>

app/views/admin/orders/show.html.erb
<div class="admin-account-page">
  <h1>Order: <%= @order.id %> </h1>
  <h2>Order Date: <%= @order.created_at %></h2>
  <h2>Order Status: <%= @order.status %></h2>
  <h2>Customer: <%= @purchaser %> </h2>
  <h2>Address: <%=  %> </h2>

  <% total = []  %>
  <%  @line_items.each do |oi| %>
  <% item = Item.find(oi.item_id)  %>
  Name: <%= item.name  %><br>
  Quantity:<%= oi.quantity %><br>
  <% subtotal = (item.price) * oi.quantity %>
  <% total << subtotal  %>
  Subtotal: <%= subtotal %><br>
  <%end  %>
  Total: <%= total.reduce(:+)  %>
</div>