config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :users, only: [:new, :create]
  resources :items, only: [:index, :show, :create, :update]
  resources :categories, only: [:index, :show]

  namespace :admin do

    get '/dashboard', to: 'dashboard#index'

    resources :orders
    resources :items
    resources :users, only: [:show]
  end

  namespace :patron do
    resources :orders, only: [:new, :create, :index, :show]
    resources :users, only: [:show, :update, :edit]
  end

  get '/dashboard', to: 'dashboard#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/cart', to: 'cart#show'
  post '/cart', to: 'cart#create'
  delete '/cart', to: 'cart#destroy'
  put '/cart', to: 'cart#update'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category

  has_many :orders_items
  has_many :orders, through: :orders_items

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/shield_item.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  extend FriendlyId
  friendly_id :name, use: :slugged

  def retired_item?
    self.status ? false : true
  end

  def in_stock?
    self.retired_item? ? "No" : "Yes"
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController

  def new
    @admin = current_user
    @item = Item.new
  end

  def index
    @items = Item.all
  end

  def edit
    @user = current_user
    @item = Item.find_by(slug: params[:id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
    @item = Item.find_by(slug: params[:id])
    @status = @item.in_stock?
  end

  def create
    @admin = current_user
    @item = Item.new(name: params[:item][:name],
                        description: params[:item][:description],
                        price: params[:item][:price].to_i,
                        category_id: params[:item][:category].to_i, avatar: params[:item][:avatar])
    if @item.save
      flash[:item_creation] = "You successfully created #{@item.name}"
      redirect_to admin_user_path(@admin)
    else
      redirect_to new_admin_item_path
    end
  end

  def update
    @item = Item.find_by(slug: params[:id])
    @item.update(item_params)
    if @item.save
      flash[:item_updated] = "You successfully updated #{@item.name}."
      redirect_to admin_items_path
    else
      flash[:item_update_failure] = "Error. Item #{@item.name} not updated."
      redirect_to request.referrer
    end
  end

  private

  def item_params
  params[:item][:price] = params[:item][:price].to_i
  params[:item][:category_id] = Category.find(params[:item][:category_id].to_i).id
  params.require(:item).permit(:name, :description, :price, :category_id, :avatar)
  end
end

app/views/items/index.html.erb
<div class="container-items">
  <div class="page-header items">
    <h1>All Items</h1>
  </div>
</div>
<div id="card-list">
    <% @items.each do |item| %>
      <div class="items">
        <figure>
          <%= image_tag item.avatar.url(:medium), class: "product" %>
          <figcaption>
            <%= link_to item.name, item_path(item) %>
            <p>Price: <%= item.price %> Rupees</p>
            <% if item.retired_item? == false %>
            <%= button_to "Add #{item.name} to Cart", cart_path(item_id: item.id), class: "btn btn-success btn-xs" %>
            <% end %>
          </figcaption>
        </figure>
        <br>
        <br>
      </div>
    <% end %>
</div>

app/views/items/show.html.erb
<div class="page-header">
  <div class="container">
    <h2><%= @item.name %></h2>
  </div>
</div>
<div class="row">
  <div class="container">
    <div class="col-sm-10 col-sm-offset-2">
      <div class="list-group">
        <ul class="col-md-8 list-unstyled">
          <img src="<%=@item.show%>">
          <!-- <%= image_tag @item.avatar.url %><br> -->
          <li class="list-group-item"><strong>Description:</strong><%= @item.description %></li>
          <li class="list-group-item"><strong>Price:</strong><%= @item.price %> Rupees</li>
          <li class="list-group-item"><strong>In Stock? </strong><%= @status %></li>
          <% if @item.retired_item? == false %>
            <%= button_to "Add #{@item.name} to Cart", cart_path(item_id: @item.id), class: "btn btn-success btn-xs" %><br>
          <% end %>
          <%= link_to "Back to all items", items_path, class: "btn btn-default btn-xs" %>
        </ul>
      </div>
    </div>
  </div>
</div>