config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :users, only: [:new, :create]
  resources :items, only: [:index, :show, :create, :update]
  resources :categories, only: [:index, :show]

  namespace :admin do

    get '/dashboard', to: 'dashboard#index'

    resources :orders
    resources :items
    resources :users, only: [:show]
  end

  namespace :patron do
    resources :orders, only: [:new, :create, :index, :show]
    resources :users, only: [:show, :update, :edit]
  end

  get '/dashboard', to: 'dashboard#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/cart', to: 'cart#show'
  post '/cart', to: 'cart#create'
  delete '/cart', to: 'cart#destroy'
  put '/cart', to: 'cart#update'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  validates :name, presence: true, uniqueness: true

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(slug: params[:id])
    @items = Item.where(category_id: @category.id)
  end
end

app/views/categories/index.html.erb
<div class="container">
  <div class="page-header categories">
    <h2>Categories</h2>
  </div>
<div>
<div class="grid">
  <% @categories.each do |category| %>
      <div class="category">
        <a href="<%= category_path(category) %>">
          <div class="thumbnail">
            <img src="/assets/<%="#{category.slug}"%>_icon.png" alt="<%= category.slug %> icon">
            <div class="caption">
              <h3><%= category.name %></h3>
            </div>
          </div>
        </a>
      </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="page-header">
<div class="container">
  <h1><%= @category.name %></h1>
</div>
</div>
<div id="card-list">
    <% @items.each do |item| %>
      <div class="items">
        <figure>
          <%= image_tag item.avatar.url(:medium), class: "product" %>
          <figcaption>
            <%= link_to item.name, item_path(item) %>
            <p>Price: <%= item.price %> Rupees</p>
            <% if item.retired_item? == false %>
            <%= button_to "Add #{item.name} to Cart", cart_path(item_id: item.id), class: "btn btn-success btn-xs" %>
            <% end %>
          </figcaption>
        </figure>
        <br>
        <br>
      </div>
    <% end %>
</div>