config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :users, only: [:new, :create]
  resources :items, only: [:index, :show, :create, :update]
  resources :categories, only: [:index, :show]

  namespace :admin do

    get '/dashboard', to: 'dashboard#index'

    resources :orders
    resources :items
    resources :users, only: [:show]
  end

  namespace :patron do
    resources :orders, only: [:new, :create, :index, :show]
    resources :users, only: [:show, :update, :edit]
  end

  get '/dashboard', to: 'dashboard#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/cart', to: 'cart#show'
  post '/cart', to: 'cart#create'
  delete '/cart', to: 'cart#destroy'
  put '/cart', to: 'cart#update'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true

  enum role: %w(patron admin)
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def show
    @user = current_user
    @orders = Order.where(user_id: @user.id).count
  end
end

app/controllers/patron/users_controller.rb
class Patron::UsersController < Patron::BaseController

  def show
    @user = current_user
    @orders = Order.where(user_id: @user.id).count
    @total = Cart.new(Order.where(user_id: @user.id)).total_spent
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:user_updated] = "You successfully updated #{@user.username}'s Profile."
      redirect_to patron_user_path(@user)
    else
      redirect_to edit_patron_user_path(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success]= "Account created successfully!"

      redirect_to "/dashboard"
    else
      flash[:error] = "U gun dun goofed"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/views/admin/users/show.html.erb
<div class="container">
  <div class="page-header admin">
      <h2><%= @user.username %>'s Account Information</h2>
  </div>
</div>
<div class="row">
  <div class="container">
      <div class="btn-toolbar pull-right">
        <%= link_to "All Orders", admin_orders_path, class: 'btn btn-default'%>
        <%= link_to "All Items", admin_items_path, class: 'btn btn-default'%>
        <%= link_to "Create Item", new_admin_item_path, class: 'btn btn-success'%>
      </div>
    <div class="col-sm-10 col-sm-offset-2">
      <div class="list-group">
        <ul class="col-md-8 list-unstyled">
          <li class="list-group-item"><strong>Username:  </strong><%= @user.username %></li>
          <li class="list-group-item"><strong>Orders Placed:  </strong><%= @orders %></li>
        </ul>
      </div>
    </div>
  </div>
</div>